 Dataset

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Bank_Customer.csv')
df

       age           job  marital  education  balance duration
0     58.0    management  married   tertiary     2143      261
1     44.0    technician   single  secondary       29      151
2     33.0  entrepreneur  married  secondary        2       76
3     47.0   blue-collar  married    unknown     1506       92
4     33.0       unknown   single    unknown        1      198
...    ...           ...      ...        ...      ...      ...
1085   NaN        admin.  married    primary      136      283
1086   NaN   blue-collar   single    unknown     2167     1273
1087   NaN   blue-collar  married  secondary      309     1574
1088   NaN    technician  married  secondary      221      139
1089   NaN   blue-collar  married    primary      321      228

[1090 rows x 6 columns]

information about the data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1090 entries, 0 to 1089
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        1000 non-null   float64
 1   job        1090 non-null   object
 2   marital    1090 non-null   object
 3   education  1090 non-null   object
 4   balance    1090 non-null   int64
 5   duration   1090 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 51.2+ KB

data with a marital of 'married'

In [ ]:
filt = (df['marital'] == 'married')
df[filt]

       age           job  marital  education  balance duration
0     58.0    management  married   tertiary     2143      261
2     33.0  entrepreneur  married  secondary        2       76
3     47.0   blue-collar  married    unknown     1506       92
5     35.0    management  married   tertiary      231      139
8     58.0       retired  married    primary      121       50
...    ...           ...      ...        ...      ...      ...
1084   NaN   blue-collar  married  secondary      615      225
1085   NaN        admin.  married    primary      136      283
1087   NaN   blue-collar  married  secondary      309     1574
1088   NaN    technician  married  secondary      221      139
1089   NaN   blue-collar  married    primary      321      228

[693 rows x 6 columns]

missing values in each column

In [ ]:
df.isna().sum()

age          90
job           0
marital       0
education     0
balance       0
duration      0
dtype: int64

Dropping the row if it has any missing values

In [ ]:
df.dropna(axis='index', how='any', inplace=True)
df

      age           job  marital  education  balance duration
0    58.0    management  married   tertiary     2143      261
1    44.0    technician   single  secondary       29      151
2    33.0  entrepreneur  married  secondary        2       76
3    47.0   blue-collar  married    unknown     1506       92
4    33.0       unknown   single    unknown        1      198
..    ...           ...      ...        ...      ...      ...
995  37.0   blue-collar  married    primary      310      474
996  34.0        admin.  married  secondary      475      559
997  43.0   blue-collar  married    primary       61      261
998  49.0      services  married  secondary     1377     1101
999  33.0    technician   single  secondary       56      236

[1000 rows x 6 columns]

Dropping the column if all its values are missing

In [ ]:
df.dropna(axis='columns', how='all', inplace=True)
df

      age           job  marital  education  balance duration
0    58.0    management  married   tertiary     2143      261
1    44.0    technician   single  secondary       29      151
2    33.0  entrepreneur  married  secondary        2       76
3    47.0   blue-collar  married    unknown     1506       92
4    33.0       unknown   single    unknown        1      198
..    ...           ...      ...        ...      ...      ...
995  37.0   blue-collar  married    primary      310      474
996  34.0        admin.  married  secondary      475      559
997  43.0   blue-collar  married    primary       61      261
998  49.0      services  married  secondary     1377     1101
999  33.0    technician   single  secondary       56      236

[1000 rows x 6 columns]

Checking if there is any duplicated values

In [ ]:
df.duplicated().any()

False

10 highest base balance

In [ ]:
df['balance'].nlargest(10)

920    58544
446    45248
334    24598
69     12223
34     10635
916     8823
391     8730
382     8486
908     7624
757     6920
Name: balance, dtype: int64

Average balance of customers

In [ ]:
df['balance'].median()

165.5

Job titles of cutomers whose balance is above average

In [ ]:
filt = (df['balance'] > df['balance'].median())

In [ ]:
df.loc[filt,['job']]

             job
0     management
3    blue-collar
5     management
6     management
9     technician
..           ...
993  blue-collar
994  blue-collar
995  blue-collar
996       admin.
998     services

[500 rows x 1 columns]

Number of customers who has the same marital status

In [ ]:
df['marital'].value_counts()

marital
married     637
single      220
divorced    143
Name: count, dtype: int64

Number of customers in each job

In [ ]:
df['job'].value_counts()

job
blue-collar      292
technician       148
admin.           141
management       137
services         131
retired           47
entrepreneur      29
self-employed     26
unemployed        23
student           13
housemaid          9
unknown            4
Name: count, dtype: int64

Cutomers with the same marital status as 'married' and same job 'management'

In [ ]:
filt = (df['marital'] == 'married') & (df['job'] == 'management')
df[filt]

      age         job  marital  education  balance duration
0    58.0  management  married   tertiary     2143      261
5    35.0  management  married   tertiary      231      139
21   56.0  management  married   tertiary      779      164
31   49.0  management  married   tertiary      378      230
34   51.0  management  married   tertiary    10635      336
..    ...         ...      ...        ...      ...      ...
948  31.0  management  married  secondary     2019      380
950  29.0  management  married  secondary      147      376
953  37.0  management  married   tertiary      115       36
962  44.0  management  married    unknown      187      185
991  33.0  management  married   tertiary      436       48

[78 rows x 6 columns]

Number of customers in each education

In [ ]:
df['education'].value_counts()

education
secondary    570
tertiary     186
primary      155
unknown       89
Name: count, dtype: int64

Average age of customers

In [ ]:
df['age'].median()

42.0

Job titles of customers whose age is above average

In [ ]:
filt = (df['age'] > df['age'].median())
df.loc[filt,['job']]

             job
0     management
1     technician
3    blue-collar
8        retired
9     technician
..           ...
984  blue-collar
986       admin.
993  blue-collar
997  blue-collar
998     services

[465 rows x 1 columns]

Customers with the same age and education

In [ ]:
## filt = df.groupby(['age','education']).filter(lambda x: len(x)>1)
## df[filt]

filt_index = df.groupby(['age','education']).filter(lambda x: len(x)>1).index
df.loc[filt_index]

      age           job  marital  education  balance duration
0    58.0    management  married   tertiary     2143      261
1    44.0    technician   single  secondary       29      151
2    33.0  entrepreneur  married  secondary        2       76
3    47.0   blue-collar  married    unknown     1506       92
5    35.0    management  married   tertiary      231      139
..    ...           ...      ...        ...      ...      ...
995  37.0   blue-collar  married    primary      310      474
996  34.0        admin.  married  secondary      475      559
997  43.0   blue-collar  married    primary       61      261
998  49.0      services  married  secondary     1377     1101
999  33.0    technician   single  secondary       56      236

[985 rows x 6 columns]